export default {
  responses: [
    { index: 1, value: true },
    { index: 2, value: true },
    { index: 3, value: true },
    { index: 4, value: true },
    { index: 5, value: true },
    { index: 6, value: true },
    { index: 7, value: true },
    { index: 8, value: true },
    { index: 9, value: false },
    { index: 10, value: true },
    { index: 11, value: false },
    { index: 12, value: true },
    { index: 13, value: true },
    { index: 14, value: true },
    { index: 15, value: false },
    { index: 16, value: false },
    { index: 17, value: true },
    { index: 18, value: false },
    { index: 19, value: true },
    { index: 20, value: false },
    { index: 21, value: true },
    { index: 22, value: false },
    { index: 23, value: false },
    { index: 24, value: true },
    { index: 25, value: true },
    { index: 26, value: true },
    { index: 27, value: false },
    { index: 28, value: true },
    { index: 29, value: true },
    { index: 30, value: false },
    { index: 31, value: true },
    { index: 32, value: true },
    { index: 33, value: true },
    { index: 34, value: true },
    { index: 35, value: true },
    { index: 36, value: true },
    { index: 37, value: true },
    { index: 38, value: true },
    { index: 39, value: true },
    { index: 40, value: false },
    { index: 41, value: true },
    { index: 42, value: true },
    { index: 43, value: true },
    { index: 44, value: true },
    { index: 45, value: true },
    { index: 46, value: false },
    { index: 47, value: true },
    { index: 48, value: true },
    { index: 49, value: true },
    { index: 50, value: true },
    { index: 51, value: true },
    { index: 52, value: true },
    { index: 53, value: true },
    { index: 54, value: true },
    { index: 55, value: true },
    { index: 56, value: true },
    { index: 57, value: true },
    { index: 58, value: true },
    { index: 59, value: true },
    { index: 60, value: true },
    { index: 61, value: true },
    { index: 62, value: true },
    { index: 63, value: true },
    { index: 64, value: true },
    { index: 65, value: false },
    { index: 66, value: true },
    { index: 67, value: true },
    { index: 68, value: true },
    { index: 69, value: false },
    { index: 70, value: false },
    { index: 71, value: true },
    { index: 72, value: false },
    { index: 73, value: true },
    { index: 74, value: true },
    { index: 75, value: true },
    { index: 76, value: true },
    { index: 77, value: false },
    { index: 78, value: true },
    { index: 79, value: true },
    { index: 80, value: true },
    { index: 81, value: true },
    { index: 82, value: true },
    { index: 83, value: true },
    { index: 84, value: true },
    { index: 85, value: true },
    { index: 86, value: true },
    { index: 87, value: false },
    { index: 88, value: true },
    { index: 89, value: true },
    { index: 90, value: true },
    { index: 91, value: true },
    { index: 92, value: false },
    { index: 93, value: true },
    { index: 94, value: true },
    { index: 95, value: false },
    { index: 96, value: true },
    { index: 97, value: true },
    { index: 98, value: true },
    { index: 99, value: true },
    { index: 100, value: true },
    { index: 101, value: true },
    { index: 102, value: false },
    { index: 103, value: false },
    { index: 104, value: true },
    { index: 105, value: false },
    { index: 106, value: true },
    { index: 107, value: true },
    { index: 108, value: true },
    { index: 109, value: true },
    { index: 110, value: false },
    { index: 111, value: true },
    { index: 112, value: false },
    { index: 113, value: false },
    { index: 114, value: true },
    { index: 115, value: true },
    { index: 116, value: true },
    { index: 117, value: true },
    { index: 118, value: true },
    { index: 119, value: false },
    { index: 120, value: true },
    { index: 121, value: false },
    { index: 122, value: false },
    { index: 123, value: true },
    { index: 124, value: true },
    { index: 125, value: true },
    { index: 126, value: true },
    { index: 127, value: true },
    { index: 128, value: true },
    { index: 129, value: true },
    { index: 130, value: false },
    { index: 131, value: true },
    { index: 132, value: true },
    { index: 133, value: true },
    { index: 134, value: true },
    { index: 135, value: true },
    { index: 136, value: true },
    { index: 137, value: true },
    { index: 138, value: true },
    { index: 139, value: true },
    { index: 140, value: true },
    { index: 141, value: true },
    { index: 142, value: true },
    { index: 143, value: false },
    { index: 144, value: true },
    { index: 145, value: true },
    { index: 146, value: false },
    { index: 147, value: true },
    { index: 148, value: true },
    { index: 149, value: true },
    { index: 150, value: true },
    { index: 151, value: true },
    { index: 152, value: true },
    { index: 153, value: false },
    { index: 154, value: true },
    { index: 155, value: true },
    { index: 156, value: true },
    { index: 157, value: false },
    { index: 158, value: true },
    { index: 159, value: false },
    { index: 160, value: true },
    { index: 161, value: true },
    { index: 162, value: true },
    { index: 163, value: false },
    { index: 164, value: true },
    { index: 165, value: true },
    { index: 166, value: true },
    { index: 167, value: true },
    { index: 168, value: true },
    { index: 169, value: true },
    { index: 170, value: false },
    { index: 171, value: true },
    { index: 172, value: false },
    { index: 173, value: true },
    { index: 174, value: true },
    { index: 175, value: true },
  ],
  result: {
    desirability: 13,
    debasement: 29,
    schizoid: 13,
    avoidant: 15,
    depressive: 19,
    dependent: 21,
    histrionic: 17,
    narcissistic: 22,
    antisocial: 21,
    sadistic: 21,
    compulsive: 15,
    negativistic: 20,
    masochistic: 16,
    schizotypal: 23,
    borderline: 19,
    paranoid: 21,
    anxiety: 17,
    somatoform: 14,
    bipolar: 16,
    dysthymia: 17,
    'alcohol-dependence': 16,
    'drug-dependence': 19,
    'post-traumatic-stress-disorder': 21,
    'thought-disorder': 19,
    'major-depression': 22,
    'delusional-disorder': 11,
    validity: 0,
  },
}
